### PR TITLE
lib.ipsec.aes_gcm: add support for AES256, extended AAD

### PR DESCRIPTION
**Pull request by eugeneia**
This extends our DynASM port of aes-gcm to support AES256. It’s a rather small change, in essence. To get there I had to:

 - update the `gcm_data` struct to make room for the extra round keys
 - parameterize the number of AES rounds (previously hard coded for AES128)
 - update some hard coded offsets that assumed things about the details above

This has overall been a very pleasant experience. Armed with the diagram below (courtesy wikipedia), the code was very approachable.

437px-gcm-galois_counter_mode_with_iv svg

### CODE REVIEW

**Comment by eugeneia** [comment]
c5a903f adds support for AAD > 16 bytes by adding the aad_prehash routine which
factors out the GHASH computation on the AAD.

The logic to load 4 to 16 bytes of AAD is moved out of inital_blocks, and
aesni_gcm_enc_avx_gen4 and aesni_gcm_dec_avx_gen4 now expect a fixed 16 byte
AAD buffer. This is compatible with how lib.ipsec.aes_128_gcm previously used
the routines: for AAD <= 16 bytes (potentially padded with zeroes) there is no
need to call aad_prehash, and aesni_gcm_enc_avx_gen4 and aesni_gcm_dec_avx_gen4
still expect the total aad length as parameters.

Bonus: calling aesni_gcm_enc_avx_gen4 and aesni_gcm_dec_avx_gen4 is now a bit
faster for AAD <= 16 bytes (padded to 16 bytes with zeroes).

**Comment by eugeneia** [comment]
There are also some new helpful comments in the AES-GCM AVX implementation source that spell out the API in detail. Using the code in #76 showed this was long overdue as the intricacies of the interface are easy to get wrong after time passes and memory fades, even if you are familiar with it. :-)

**Comment by lukego** [comment]
Great hacking @eugeneia! I love following this stuff :-)

**Comment by eugeneia** [comment]
Before pushing this to upstream Snabb it might be sensible to extend the test cases to include test comprehensive test vectors from project [wycheproof](https://github.com/google/wycheproof) and NIST etc.

I think this is a really neat, maintainable implementation of AES-GCM. We could show this by polishing our test coverage and advertising that we conform with the mentioned test vector suites.

**Comment by eugeneia** [comment]
@lukego That’s always nice to hear, thanks! :-)

FWIW, the NIST document “Recommendation for Block Cipher Modes of Operation: Galois/Counter Mode (GCM) and GMAC” contains the descriptions of AES-GCM based on which the AAD extension hack is done. There are two ingredients to this change really, first a description of the underlying GHASH function used to compute the authentication tag:

Screenshot from 2019-03-27 12-51-23

And then the AES-GCM AEAD algorithm as a whole that shows how GHASH fits into the big picture:

Screenshot from 2019-03-27 12-51-05

The key issue here was realizing that you can extract (“factor out”, as my math friend @ioannad explained to me) the AAD chunk of the GHASH computation since you can view its result as just another input to the remaining tag computation.

Fun: there are three different descriptions of GHASH in that document, one algorithmic, one mathematical, and one as a diagram (shown above). I like the diagram the most, and the mathematical description confused me. @ioannad preferred the mathematical formula over the diagram. Different languages for different minds? :-)

**Pull request merged**
